# =====================================================================
# 1. КОНФІГУРАЦІЯ ДЛЯ NODE EXPORTER (https://my.domen)
# =====================================================================
server {
    server_name node.my.domen;

    location / {
        # Захист метрик паролем за допомогою Basic Auth
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://127.0.0.1:9100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/node.my.domen/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/node.my.domen/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = node.my.domen) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name node.my.domen;
    return 404; # managed by Certbot
}


# =====================================================================
# 2. КОНФІГУРАЦІЯ ДЛЯ PORTAINER AGENT (https://my.domen)
# =====================================================================
server {
    server_name docker-portainer.my.domen;

    location / {
        # Проксіювання зашифрованого gRPC трафіку в контейнер агента
        grpc_pass grpcs://127.0.0.1:9001;
        grpc_ssl_verify off;

        # Передача обов'язкових заголовків для gRPC
        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto $scheme;

        # Таймаути для стабільних довгоживучих з'єднань (веб-сокети/стріми)
        grpc_read_timeout 86400s;
        grpc_send_timeout 86400s;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/docker-portainer.my.domen/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/docker-portainer.my.domen/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = docker-portainer.my.domen) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;
    server_name docker-portainer.my.domen;
    return 404; # managed by Certbot
}
